---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketrequests", "bucketaccessrequests", "bucketrequests/status", "bucketaccessrequests/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketclasses","bucketaccessclasses"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "serviceaccounts"]
  verbs: ["list", "get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
subjects:
  - kind: ServiceAccount
    name: objectstorage-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: objectstorage-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller
  namespace: default
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
subjects:
  - kind: ServiceAccount
    name: objectstorage-controller-sa
    namespace: default
roleRef:
  kind: Role
  name: objectstorage-controller
  apiGroup: rbac.authorization.k8s.io
